name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: "devkitpro/devkitarm:latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=cmake/devkitarm-toolchain.cmake

      - name: Build
        run: |
          cmake -B build --build
